// Copyright 2026 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.
// This file is generated by ts-to-schema, do not edit it directly.
// @ts-nocheck
/* cspell:disable */
import type { ICompiledValidator } from "@twin.org/data-core";
import * as external0 from "@twin.org/data-json-ld";
const MESSAGES = ["must be equal to constant","must NOT have fewer than 1 items","must match a schema in anyOf","must contain at least 1 and no more than 1 valid item(s)","must be array","must be string","must be object","must be number"];
function createError(instancePath, schemaPath, keyword, params, message) {
return { instancePath, schemaPath, keyword, params, ["message"]: typeof message === "number" ? MESSAGES[message] : message };
}
function pushError(errors, error) {
if (errors === null) {
return [error];
}
errors.push(error);
return errors;
}
/**
 * Compiled validator for the FoafContextType schema.
 */
export const CompiledFoafContextType: ICompiledValidator = validate52;
const keyword0 = external0["CompiledJsonLdContextDefinitionElement"];

function validate52(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/foaf/FoafContextType" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate52.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
const _errs0 = errors;
let valid0 = false;
const _errs1 = errors;
if("https://xmlns.com/foaf/0.1/" !== data){
const err0 = createError(instancePath,"#/anyOf/0/const","const",{allowedValue: "https://xmlns.com/foaf/0.1/"},0);
vErrors = pushError(vErrors, err0);
errors++;
}
var _valid0 = _errs1 === errors;
valid0 = valid0 || _valid0;
const _errs2 = errors;
if(Array.isArray(data)){
if(data.length < 1){
const err1 = createError(instancePath,"#/anyOf/1/minItems","minItems",{limit: 1},1);
vErrors = pushError(vErrors, err1);
errors++;
}
const len0 = data.length;
for(let i0=0; i0<len0; i0++){
let data0 = data[i0];
const _errs5 = errors;
let valid3 = false;
const _errs6 = errors;
if(!(keyword0(data0, {instancePath:instancePath+"/" + i0,parentData:data,parentDataProperty:i0,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword0.errors : vErrors.concat(keyword0.errors);
errors = vErrors.length;
}
var _valid1 = _errs6 === errors;
valid3 = valid3 || _valid1;
const _errs7 = errors;
if("https://xmlns.com/foaf/0.1/" !== data0){
const err2 = createError(instancePath+"/" + i0,"#/anyOf/1/items/anyOf/1/const","const",{allowedValue: "https://xmlns.com/foaf/0.1/"},0);
vErrors = pushError(vErrors, err2);
errors++;
}
var _valid1 = _errs7 === errors;
valid3 = valid3 || _valid1;
if(!valid3){
const err3 = createError(instancePath+"/" + i0,"#/anyOf/1/items/anyOf","anyOf",{},2);
vErrors = pushError(vErrors, err3);
errors++;
}
else {
errors = _errs5;
if(vErrors !== null){
if(_errs5){
vErrors.length = _errs5;
}
else {
vErrors = null;
}
}
}
}
const _errs8 = errors;
const len1 = data.length;
let valid4 = false;
let count0 = 0;
for(let i1=0; i1<len1; i1++){
const _errs9 = errors;
if("https://xmlns.com/foaf/0.1/" !== data[i1]){
const err4 = createError(instancePath+"/" + i1,"#/anyOf/1/contains/const","const",{allowedValue: "https://xmlns.com/foaf/0.1/"},0);
vErrors = pushError(vErrors, err4);
errors++;
}
var _valid2 = _errs9 === errors;
if(_valid2){
count0++;
if(count0 > 1){
valid4 = false;
break;
}
valid4 = true;
}
}
if(!valid4){
const err5 = createError(instancePath,"#/anyOf/1/contains","contains",{minContains: 1, maxContains: 1},3);
vErrors = pushError(vErrors, err5);
errors++;
}
else {
errors = _errs8;
if(vErrors !== null){
if(_errs8){
vErrors.length = _errs8;
}
else {
vErrors = null;
}
}
}
}
else {
const err6 = createError(instancePath,"#/anyOf/1/type","type",{type: "array"},4);
vErrors = pushError(vErrors, err6);
errors++;
}
var _valid0 = _errs2 === errors;
valid0 = valid0 || _valid0;
if(_valid0){
var items0 = true;
}
if(!valid0){
const err7 = createError(instancePath,"#/anyOf","anyOf",{},2);
vErrors = pushError(vErrors, err7);
errors++;
}
else {
errors = _errs0;
if(vErrors !== null){
if(_errs0){
vErrors.length = _errs0;
}
else {
vErrors = null;
}
}
}
validate52.errors = vErrors;
evaluated0.items = items0;
return errors === 0;
}
validate52.evaluated = {"dynamicProps":false,"dynamicItems":true};

/**
 * Compiled validator for the FoafAgent schema.
 */
export const CompiledFoafAgent: ICompiledValidator = validate53;
const wrapper0 = {validate: validate54};
const keyword1 = external0["CompiledJsonLdNodeObject"];

function validate57(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/foaf/FoafDocument" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate57.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(!(wrapper0.validate(data, {instancePath,parentData,parentDataProperty,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? wrapper0.validate.errors : vErrors.concat(wrapper0.validate.errors);
errors = vErrors.length;
}
else {
var props0 = wrapper0.validate.evaluated.props;
var items0 = wrapper0.validate.evaluated.items;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data["@type"] === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "@type"},"must have required property '"+"@type"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(props0 !== true){
props0 = props0 || {};
props0["@context"] = true;
props0["@type"] = true;
props0.topic = true;
props0.primaryTopic = true;
props0.sha1 = true;
}
if(data["@context"] !== undefined){
if(!(validate52(data["@context"], {instancePath:instancePath+"/@context",parentData:data,parentDataProperty:"@context",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate52.errors : vErrors.concat(validate52.errors);
errors = vErrors.length;
}
}
if(data["@type"] !== undefined){
let data1 = data["@type"];
const _errs4 = errors;
let valid2 = false;
const _errs5 = errors;
if("Document" !== data1){
const err1 = createError(instancePath+"/@type","#/properties/%40type/anyOf/0/const","const",{allowedValue: "Document"},0);
vErrors = pushError(vErrors, err1);
errors++;
}
var _valid0 = _errs5 === errors;
valid2 = valid2 || _valid0;
const _errs6 = errors;
if("Image" !== data1){
const err2 = createError(instancePath+"/@type","#/properties/%40type/anyOf/1/const","const",{allowedValue: "Image"},0);
vErrors = pushError(vErrors, err2);
errors++;
}
var _valid0 = _errs6 === errors;
valid2 = valid2 || _valid0;
if(!valid2){
const err3 = createError(instancePath+"/@type","#/properties/%40type/anyOf","anyOf",{},2);
vErrors = pushError(vErrors, err3);
errors++;
}
else {
errors = _errs4;
if(vErrors !== null){
if(_errs4){
vErrors.length = _errs4;
}
else {
vErrors = null;
}
}
}
}
if(data.topic !== undefined){
if(typeof data.topic !== "string"){
const err4 = createError(instancePath+"/topic","#/properties/topic/type","type",{type: "string"},5);
vErrors = pushError(vErrors, err4);
errors++;
}
}
if(data.primaryTopic !== undefined){
let data3 = data.primaryTopic;
const _errs10 = errors;
let valid3 = false;
const _errs11 = errors;
if(!(keyword1(data3, {instancePath:instancePath+"/primaryTopic",parentData:data,parentDataProperty:"primaryTopic",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
errors = vErrors.length;
}
var _valid1 = _errs11 === errors;
valid3 = valid3 || _valid1;
const _errs12 = errors;
if(Array.isArray(data3)){
const len0 = data3.length;
for(let i0=0; i0<len0; i0++){
if(!(keyword1(data3[i0], {instancePath:instancePath+"/primaryTopic/" + i0,parentData:data3,parentDataProperty:i0,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
errors = vErrors.length;
}
}
}
else {
const err5 = createError(instancePath+"/primaryTopic","#/properties/primaryTopic/anyOf/1/type","type",{type: "array"},4);
vErrors = pushError(vErrors, err5);
errors++;
}
var _valid1 = _errs12 === errors;
valid3 = valid3 || _valid1;
if(!valid3){
const err6 = createError(instancePath+"/primaryTopic","#/properties/primaryTopic/anyOf","anyOf",{},2);
vErrors = pushError(vErrors, err6);
errors++;
}
else {
errors = _errs10;
if(vErrors !== null){
if(_errs10){
vErrors.length = _errs10;
}
else {
vErrors = null;
}
}
}
}
if(data.sha1 !== undefined){
if(typeof data.sha1 !== "string"){
const err7 = createError(instancePath+"/sha1","#/properties/sha1/type","type",{type: "string"},5);
vErrors = pushError(vErrors, err7);
errors++;
}
}
}
else {
const err8 = createError(instancePath,"#/type","type",{type: "object"},6);
vErrors = pushError(vErrors, err8);
errors++;
}
validate57.errors = vErrors;
evaluated0.props = props0;
evaluated0.items = items0;
return errors === 0;
}
validate57.evaluated = {"dynamicProps":true,"dynamicItems":true};

const wrapper1 = {validate: validate56};

function validate56(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/foaf/FoafImage" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate56.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(!(validate57(data, {instancePath,parentData,parentDataProperty,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate57.errors : vErrors.concat(validate57.errors);
errors = vErrors.length;
}
else {
var props0 = validate57.evaluated.props;
var items0 = validate57.evaluated.items;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data["@type"] === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "@type"},"must have required property '"+"@type"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(props0 !== true){
props0 = props0 || {};
props0["@context"] = true;
props0["@type"] = true;
props0.depicts = true;
props0.thumbnail = true;
}
if(data["@context"] !== undefined){
if(!(validate52(data["@context"], {instancePath:instancePath+"/@context",parentData:data,parentDataProperty:"@context",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate52.errors : vErrors.concat(validate52.errors);
errors = vErrors.length;
}
}
if(data["@type"] !== undefined){
if("Image" !== data["@type"]){
const err1 = createError(instancePath+"/@type","#/properties/%40type/const","const",{allowedValue: "Image"},0);
vErrors = pushError(vErrors, err1);
errors++;
}
}
if(data.depicts !== undefined){
if(!(keyword1(data.depicts, {instancePath:instancePath+"/depicts",parentData:data,parentDataProperty:"depicts",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
errors = vErrors.length;
}
}
if(data.thumbnail !== undefined){
if(!(wrapper1.validate(data.thumbnail, {instancePath:instancePath+"/thumbnail",parentData:data,parentDataProperty:"thumbnail",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? wrapper1.validate.errors : vErrors.concat(wrapper1.validate.errors);
errors = vErrors.length;
}
}
}
else {
const err2 = createError(instancePath,"#/type","type",{type: "object"},6);
vErrors = pushError(vErrors, err2);
errors++;
}
validate56.errors = vErrors;
evaluated0.props = props0;
evaluated0.items = items0;
return errors === 0;
}
validate56.evaluated = {"dynamicProps":true,"dynamicItems":true};


function validate54(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/foaf/FoafBaseObject" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate54.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data["@context"] !== undefined){
if(!(validate52(data["@context"], {instancePath:instancePath+"/@context",parentData:data,parentDataProperty:"@context",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate52.errors : vErrors.concat(validate52.errors);
errors = vErrors.length;
}
}
if(data["@id"] !== undefined){
if(typeof data["@id"] !== "string"){
const err0 = createError(instancePath+"/@id","#/properties/%40id/type","type",{type: "string"},5);
vErrors = pushError(vErrors, err0);
errors++;
}
}
if(data.name !== undefined){
if(typeof data.name !== "string"){
const err1 = createError(instancePath+"/name","#/properties/name/type","type",{type: "string"},5);
vErrors = pushError(vErrors, err1);
errors++;
}
}
if(data.title !== undefined){
if(typeof data.title !== "string"){
const err2 = createError(instancePath+"/title","#/properties/title/type","type",{type: "string"},5);
vErrors = pushError(vErrors, err2);
errors++;
}
}
if(data.mbox !== undefined){
if(typeof data.mbox !== "string"){
const err3 = createError(instancePath+"/mbox","#/properties/mbox/type","type",{type: "string"},5);
vErrors = pushError(vErrors, err3);
errors++;
}
}
if(data.homepage !== undefined){
if(typeof data.homepage !== "string"){
const err4 = createError(instancePath+"/homepage","#/properties/homepage/type","type",{type: "string"},5);
vErrors = pushError(vErrors, err4);
errors++;
}
}
if(data.depiction !== undefined){
if(!(validate56(data.depiction, {instancePath:instancePath+"/depiction",parentData:data,parentDataProperty:"depiction",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate56.errors : vErrors.concat(validate56.errors);
errors = vErrors.length;
}
}
}
else {
const err5 = createError(instancePath,"#/type","type",{type: "object"},6);
vErrors = pushError(vErrors, err5);
errors++;
}
validate54.errors = vErrors;
return errors === 0;
}
validate54.evaluated = {"props":{"@context":true,"@id":true,"name":true,"title":true,"mbox":true,"homepage":true,"depiction":true},"dynamicProps":false,"dynamicItems":false};


function validate53(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/foaf/FoafAgent" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate53.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(!(validate54(data, {instancePath,parentData,parentDataProperty,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate54.errors : vErrors.concat(validate54.errors);
errors = vErrors.length;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data["@type"] === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "@type"},"must have required property '"+"@type"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(data["@context"] !== undefined){
if(!(validate52(data["@context"], {instancePath:instancePath+"/@context",parentData:data,parentDataProperty:"@context",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate52.errors : vErrors.concat(validate52.errors);
errors = vErrors.length;
}
}
if(data["@type"] !== undefined){
let data1 = data["@type"];
const _errs4 = errors;
let valid2 = false;
const _errs5 = errors;
if("Agent" !== data1){
const err1 = createError(instancePath+"/@type","#/properties/%40type/anyOf/0/const","const",{allowedValue: "Agent"},0);
vErrors = pushError(vErrors, err1);
errors++;
}
var _valid0 = _errs5 === errors;
valid2 = valid2 || _valid0;
const _errs6 = errors;
if("Person" !== data1){
const err2 = createError(instancePath+"/@type","#/properties/%40type/anyOf/1/const","const",{allowedValue: "Person"},0);
vErrors = pushError(vErrors, err2);
errors++;
}
var _valid0 = _errs6 === errors;
valid2 = valid2 || _valid0;
const _errs7 = errors;
if("Organization" !== data1){
const err3 = createError(instancePath+"/@type","#/properties/%40type/anyOf/2/const","const",{allowedValue: "Organization"},0);
vErrors = pushError(vErrors, err3);
errors++;
}
var _valid0 = _errs7 === errors;
valid2 = valid2 || _valid0;
const _errs8 = errors;
if("Group" !== data1){
const err4 = createError(instancePath+"/@type","#/properties/%40type/anyOf/3/const","const",{allowedValue: "Group"},0);
vErrors = pushError(vErrors, err4);
errors++;
}
var _valid0 = _errs8 === errors;
valid2 = valid2 || _valid0;
const _errs9 = errors;
if(typeof data1 !== "string"){
const err5 = createError(instancePath+"/@type","#/properties/%40type/anyOf/4/type","type",{type: "string"},5);
vErrors = pushError(vErrors, err5);
errors++;
}
var _valid0 = _errs9 === errors;
valid2 = valid2 || _valid0;
if(!valid2){
const err6 = createError(instancePath+"/@type","#/properties/%40type/anyOf","anyOf",{},2);
vErrors = pushError(vErrors, err6);
errors++;
}
else {
errors = _errs4;
if(vErrors !== null){
if(_errs4){
vErrors.length = _errs4;
}
else {
vErrors = null;
}
}
}
}
if(data.age !== undefined){
let data2 = data.age;
if(!((typeof data2 == "number") && (isFinite(data2)))){
const err7 = createError(instancePath+"/age","#/properties/age/type","type",{type: "number"},7);
vErrors = pushError(vErrors, err7);
errors++;
}
}
if(data.made !== undefined){
let data3 = data.made;
const _errs14 = errors;
let valid3 = false;
const _errs15 = errors;
if(!(keyword1(data3, {instancePath:instancePath+"/made",parentData:data,parentDataProperty:"made",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
errors = vErrors.length;
}
var _valid1 = _errs15 === errors;
valid3 = valid3 || _valid1;
const _errs16 = errors;
if(Array.isArray(data3)){
const len0 = data3.length;
for(let i0=0; i0<len0; i0++){
if(!(keyword1(data3[i0], {instancePath:instancePath+"/made/" + i0,parentData:data3,parentDataProperty:i0,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
errors = vErrors.length;
}
}
}
else {
const err8 = createError(instancePath+"/made","#/properties/made/anyOf/1/type","type",{type: "array"},4);
vErrors = pushError(vErrors, err8);
errors++;
}
var _valid1 = _errs16 === errors;
valid3 = valid3 || _valid1;
if(!valid3){
const err9 = createError(instancePath+"/made","#/properties/made/anyOf","anyOf",{},2);
vErrors = pushError(vErrors, err9);
errors++;
}
else {
errors = _errs14;
if(vErrors !== null){
if(_errs14){
vErrors.length = _errs14;
}
else {
vErrors = null;
}
}
}
}
if(data.weblog !== undefined){
if(!(validate57(data.weblog, {instancePath:instancePath+"/weblog",parentData:data,parentDataProperty:"weblog",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate57.errors : vErrors.concat(validate57.errors);
errors = vErrors.length;
}
}
if(data.openid !== undefined){
if(!(validate57(data.openid, {instancePath:instancePath+"/openid",parentData:data,parentDataProperty:"openid",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate57.errors : vErrors.concat(validate57.errors);
errors = vErrors.length;
}
}
if(data.interest !== undefined){
if(!(validate57(data.interest, {instancePath:instancePath+"/interest",parentData:data,parentDataProperty:"interest",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate57.errors : vErrors.concat(validate57.errors);
errors = vErrors.length;
}
}
if(data.topic_interest !== undefined){
if(!(keyword1(data.topic_interest, {instancePath:instancePath+"/topic_interest",parentData:data,parentDataProperty:"topic_interest",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
errors = vErrors.length;
}
}
}
else {
const err10 = createError(instancePath,"#/type","type",{type: "object"},6);
vErrors = pushError(vErrors, err10);
errors++;
}
validate53.errors = vErrors;
return errors === 0;
}
validate53.evaluated = {"props":{"@context":true,"@type":true,"age":true,"made":true,"weblog":true,"openid":true,"interest":true,"topic_interest":true,"@id":true,"name":true,"title":true,"mbox":true,"homepage":true,"depiction":true},"dynamicProps":false,"dynamicItems":false};

/**
 * Compiled validator for the FoafBaseObject schema.
 */
export const CompiledFoafBaseObject: ICompiledValidator = validate54;

/**
 * Compiled validator for the FoafDocument schema.
 */
export const CompiledFoafDocument: ICompiledValidator = validate57;

/**
 * Compiled validator for the FoafGroup schema.
 */
export const CompiledFoafGroup: ICompiledValidator = validate67;

function validate67(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/foaf/FoafGroup" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate67.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(!(validate53(data, {instancePath,parentData,parentDataProperty,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate53.errors : vErrors.concat(validate53.errors);
errors = vErrors.length;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data["@type"] === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "@type"},"must have required property '"+"@type"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(data["@context"] !== undefined){
if(!(validate52(data["@context"], {instancePath:instancePath+"/@context",parentData:data,parentDataProperty:"@context",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate52.errors : vErrors.concat(validate52.errors);
errors = vErrors.length;
}
}
if(data["@type"] !== undefined){
if("Group" !== data["@type"]){
const err1 = createError(instancePath+"/@type","#/properties/%40type/const","const",{allowedValue: "Group"},0);
vErrors = pushError(vErrors, err1);
errors++;
}
}
if(data.member !== undefined){
let data2 = data.member;
const _errs5 = errors;
let valid2 = false;
const _errs6 = errors;
if(!(validate53(data2, {instancePath:instancePath+"/member",parentData:data,parentDataProperty:"member",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate53.errors : vErrors.concat(validate53.errors);
errors = vErrors.length;
}
var _valid0 = _errs6 === errors;
valid2 = valid2 || _valid0;
if(_valid0){
var props0 = {};
props0["@context"] = true;
props0["@type"] = true;
props0.age = true;
props0.made = true;
props0.weblog = true;
props0.openid = true;
props0.interest = true;
props0.topic_interest = true;
props0["@id"] = true;
props0.name = true;
props0.title = true;
props0.mbox = true;
props0.homepage = true;
props0.depiction = true;
}
const _errs7 = errors;
if(Array.isArray(data2)){
const len0 = data2.length;
for(let i0=0; i0<len0; i0++){
if(!(validate53(data2[i0], {instancePath:instancePath+"/member/" + i0,parentData:data2,parentDataProperty:i0,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate53.errors : vErrors.concat(validate53.errors);
errors = vErrors.length;
}
}
}
else {
const err2 = createError(instancePath+"/member","#/properties/member/anyOf/1/type","type",{type: "array"},4);
vErrors = pushError(vErrors, err2);
errors++;
}
var _valid0 = _errs7 === errors;
valid2 = valid2 || _valid0;
if(!valid2){
const err3 = createError(instancePath+"/member","#/properties/member/anyOf","anyOf",{},2);
vErrors = pushError(vErrors, err3);
errors++;
}
else {
errors = _errs5;
if(vErrors !== null){
if(_errs5){
vErrors.length = _errs5;
}
else {
vErrors = null;
}
}
}
}
}
else {
const err4 = createError(instancePath,"#/type","type",{type: "object"},6);
vErrors = pushError(vErrors, err4);
errors++;
}
validate67.errors = vErrors;
return errors === 0;
}
validate67.evaluated = {"props":{"@context":true,"@type":true,"member":true,"age":true,"made":true,"weblog":true,"openid":true,"interest":true,"topic_interest":true,"@id":true,"name":true,"title":true,"mbox":true,"homepage":true,"depiction":true},"dynamicProps":false,"dynamicItems":false};

/**
 * Compiled validator for the FoafImage schema.
 */
export const CompiledFoafImage: ICompiledValidator = validate56;

/**
 * Compiled validator for the FoafOrganization schema.
 */
export const CompiledFoafOrganization: ICompiledValidator = validate72;

function validate72(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/foaf/FoafOrganization" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate72.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(!(validate53(data, {instancePath,parentData,parentDataProperty,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate53.errors : vErrors.concat(validate53.errors);
errors = vErrors.length;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data["@type"] === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "@type"},"must have required property '"+"@type"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(data["@context"] !== undefined){
if(!(validate52(data["@context"], {instancePath:instancePath+"/@context",parentData:data,parentDataProperty:"@context",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate52.errors : vErrors.concat(validate52.errors);
errors = vErrors.length;
}
}
if(data["@type"] !== undefined){
if("Organization" !== data["@type"]){
const err1 = createError(instancePath+"/@type","#/properties/%40type/const","const",{allowedValue: "Organization"},0);
vErrors = pushError(vErrors, err1);
errors++;
}
}
}
else {
const err2 = createError(instancePath,"#/type","type",{type: "object"},6);
vErrors = pushError(vErrors, err2);
errors++;
}
validate72.errors = vErrors;
return errors === 0;
}
validate72.evaluated = {"props":{"@context":true,"@type":true,"age":true,"made":true,"weblog":true,"openid":true,"interest":true,"topic_interest":true,"@id":true,"name":true,"title":true,"mbox":true,"homepage":true,"depiction":true},"dynamicProps":false,"dynamicItems":false};

/**
 * Compiled validator for the FoafPerson schema.
 */
export const CompiledFoafPerson: ICompiledValidator = validate75;

function validate75(data, {instancePath="", parentData, parentDataProperty, rootData=data, dynamicAnchors={}}={}){
/*# sourceURL="https://schema.twindev.org/foaf/FoafPerson" */;
let vErrors = null;
let errors = 0;
const evaluated0 = validate75.evaluated;
if(evaluated0.dynamicProps){
evaluated0.props = undefined;
}
if(evaluated0.dynamicItems){
evaluated0.items = undefined;
}
if(!(validate53(data, {instancePath,parentData,parentDataProperty,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate53.errors : vErrors.concat(validate53.errors);
errors = vErrors.length;
}
if(data && typeof data == "object" && !Array.isArray(data)){
if(data["@type"] === undefined){
const err0 = createError(instancePath,"#/required","required",{missingProperty: "@type"},"must have required property '"+"@type"+"'");
vErrors = pushError(vErrors, err0);
errors++;
}
if(data["@context"] !== undefined){
if(!(validate52(data["@context"], {instancePath:instancePath+"/@context",parentData:data,parentDataProperty:"@context",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate52.errors : vErrors.concat(validate52.errors);
errors = vErrors.length;
}
}
if(data["@type"] !== undefined){
if("Person" !== data["@type"]){
const err1 = createError(instancePath+"/@type","#/properties/%40type/const","const",{allowedValue: "Person"},0);
vErrors = pushError(vErrors, err1);
errors++;
}
}
if(data.familyName !== undefined){
if(typeof data.familyName !== "string"){
const err2 = createError(instancePath+"/familyName","#/properties/familyName/type","type",{type: "string"},5);
vErrors = pushError(vErrors, err2);
errors++;
}
}
if(data.givenName !== undefined){
if(typeof data.givenName !== "string"){
const err3 = createError(instancePath+"/givenName","#/properties/givenName/type","type",{type: "string"},5);
vErrors = pushError(vErrors, err3);
errors++;
}
}
if(data.knows !== undefined){
let data4 = data.knows;
const _errs9 = errors;
let valid2 = false;
const _errs10 = errors;
if(!(validate53(data4, {instancePath:instancePath+"/knows",parentData:data,parentDataProperty:"knows",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate53.errors : vErrors.concat(validate53.errors);
errors = vErrors.length;
}
var _valid0 = _errs10 === errors;
valid2 = valid2 || _valid0;
if(_valid0){
var props0 = {};
props0["@context"] = true;
props0["@type"] = true;
props0.age = true;
props0.made = true;
props0.weblog = true;
props0.openid = true;
props0.interest = true;
props0.topic_interest = true;
props0["@id"] = true;
props0.name = true;
props0.title = true;
props0.mbox = true;
props0.homepage = true;
props0.depiction = true;
}
const _errs11 = errors;
if(Array.isArray(data4)){
const len0 = data4.length;
for(let i0=0; i0<len0; i0++){
if(!(validate53(data4[i0], {instancePath:instancePath+"/knows/" + i0,parentData:data4,parentDataProperty:i0,rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate53.errors : vErrors.concat(validate53.errors);
errors = vErrors.length;
}
}
}
else {
const err4 = createError(instancePath+"/knows","#/properties/knows/anyOf/1/type","type",{type: "array"},4);
vErrors = pushError(vErrors, err4);
errors++;
}
var _valid0 = _errs11 === errors;
valid2 = valid2 || _valid0;
if(!valid2){
const err5 = createError(instancePath+"/knows","#/properties/knows/anyOf","anyOf",{},2);
vErrors = pushError(vErrors, err5);
errors++;
}
else {
errors = _errs9;
if(vErrors !== null){
if(_errs9){
vErrors.length = _errs9;
}
else {
vErrors = null;
}
}
}
}
if(data.img !== undefined){
if(!(validate56(data.img, {instancePath:instancePath+"/img",parentData:data,parentDataProperty:"img",rootData,dynamicAnchors}))){
vErrors = vErrors === null ? validate56.errors : vErrors.concat(validate56.errors);
errors = vErrors.length;
}
}
if(data.nick !== undefined){
if(typeof data.nick !== "string"){
const err6 = createError(instancePath+"/nick","#/properties/nick/type","type",{type: "string"},5);
vErrors = pushError(vErrors, err6);
errors++;
}
}
}
else {
const err7 = createError(instancePath,"#/type","type",{type: "object"},6);
vErrors = pushError(vErrors, err7);
errors++;
}
validate75.errors = vErrors;
return errors === 0;
}
validate75.evaluated = {"props":{"@context":true,"@type":true,"familyName":true,"givenName":true,"knows":true,"img":true,"nick":true,"age":true,"made":true,"weblog":true,"openid":true,"interest":true,"topic_interest":true,"@id":true,"name":true,"title":true,"mbox":true,"homepage":true,"depiction":true},"dynamicProps":false,"dynamicItems":false};

