// Copyright 2026 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.
// This file is generated by ts-to-schema, do not edit it directly.
// @ts-nocheck
/* cspell:disable */
import type { ICompiledValidator } from "@3sixty/data-core";

const MESSAGES = ["must be equal to constant", "must be string", "must be object"];
function createError(instancePath, schemaPath, keyword, params, message) {
	return {
		instancePath,
		schemaPath,
		keyword,
		params,
		["message"]: typeof message === "number" ? MESSAGES[message] : message
	};
}
function pushError(errors, error) {
	if (errors === null) {
		return [error];
	}
	errors.push(error);
	return errors;
}
/**
 * Compiled validator for the DublinCorePeriodOfTime schema.
 */
export const CompiledDublinCorePeriodOfTime: ICompiledValidator = validate52;

function validate52(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/dublin-core/DublinCorePeriodOfTime" */ let vErrors =
		null;
	let errors = 0;
	const evaluated0 = validate52.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data["@type"] !== undefined) {
			if ("PeriodOfTime" !== data["@type"]) {
				const err0 = createError(
					instancePath + "/@type",
					"#/properties/%40type/const",
					"const",
					{ allowedValue: "PeriodOfTime" },
					0
				);
				vErrors = pushError(vErrors, err0);
				errors++;
			}
		}
		if (data["dcat:startDate"] !== undefined) {
			if (typeof data["dcat:startDate"] !== "string") {
				const err1 = createError(
					instancePath + "/dcat:startDate",
					"#/properties/dcat%3AstartDate/type",
					"type",
					{ type: "string" },
					1
				);
				vErrors = pushError(vErrors, err1);
				errors++;
			}
		}
		if (data["dcat:endDate"] !== undefined) {
			if (typeof data["dcat:endDate"] !== "string") {
				const err2 = createError(
					instancePath + "/dcat:endDate",
					"#/properties/dcat%3AendDate/type",
					"type",
					{ type: "string" },
					1
				);
				vErrors = pushError(vErrors, err2);
				errors++;
			}
		}
		if (data["time:hasBeginning"] !== undefined) {
			if (typeof data["time:hasBeginning"] !== "string") {
				const err3 = createError(
					instancePath + "/time:hasBeginning",
					"#/properties/time%3AhasBeginning/type",
					"type",
					{ type: "string" },
					1
				);
				vErrors = pushError(vErrors, err3);
				errors++;
			}
		}
		if (data["time:hasEnd"] !== undefined) {
			if (typeof data["time:hasEnd"] !== "string") {
				const err4 = createError(
					instancePath + "/time:hasEnd",
					"#/properties/time%3AhasEnd/type",
					"type",
					{ type: "string" },
					1
				);
				vErrors = pushError(vErrors, err4);
				errors++;
			}
		}
	} else {
		const err5 = createError(instancePath, "#/type", "type", { type: "object" }, 2);
		vErrors = pushError(vErrors, err5);
		errors++;
	}
	validate52.errors = vErrors;
	return errors === 0;
}
validate52.evaluated = {
	props: {
		"@type": true,
		"dcat:startDate": true,
		"dcat:endDate": true,
		"time:hasBeginning": true,
		"time:hasEnd": true
	},
	dynamicProps: false,
	dynamicItems: false
};
